{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.funmake",
    "module": "retrofit-spring-adapter",
    "version": "0204.0209.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "qm2cg6ea4vhmxpt6qjnsrlrnmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.0-RC2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "5.3.0-RC2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "retrofit-spring-adapter-0204.0209.0.jar",
          "url": "retrofit-spring-adapter-0204.0209.0.jar",
          "size": 32782,
          "sha512": "ec1434c4de55b4231e0361c5605b15eb0d8c0071b746c1aa173b3f8bcefbe32d383f3320b188ba802d860ab563648429bf86d1f7860da5bdfb6c866bc0ae5e97",
          "sha256": "f41ffb536451a6b2f9959d7d17666b516f4be0eed6c49d9bf33c0f36ad56ae06",
          "sha1": "920ae9c604ffc9c64695ba504c9ea6d33154d174",
          "md5": "6cd85674e5e5fd36200d7be6935e6653"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.0-RC2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "5.3.0-RC2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "retrofit-spring-adapter-0204.0209.0.jar",
          "url": "retrofit-spring-adapter-0204.0209.0.jar",
          "size": 32782,
          "sha512": "ec1434c4de55b4231e0361c5605b15eb0d8c0071b746c1aa173b3f8bcefbe32d383f3320b188ba802d860ab563648429bf86d1f7860da5bdfb6c866bc0ae5e97",
          "sha256": "f41ffb536451a6b2f9959d7d17666b516f4be0eed6c49d9bf33c0f36ad56ae06",
          "sha1": "920ae9c604ffc9c64695ba504c9ea6d33154d174",
          "md5": "6cd85674e5e5fd36200d7be6935e6653"
        }
      ]
    }
  ]
}
